# hosts/server/configuration.nix
{ config, lib, pkgs, inputs, ... }: {
  imports = [
    # Hardware configuration (auto-generated by NixOS — kernel modules, CPU, etc.)
    ./hardware-configuration.nix

    # Disko: declarative disk partitioning (replaces fileSystems in hardware-configuration.nix)
    inputs.disko.nixosModules.disko   # Disko NixOS module (from flake inputs)
    ./disko-config.nix                # Your disk layout (sets disko.devices)

    # Feature modules
    ../../modules/common/nix-settings.nix
    ../../modules/common/timezone.nix
    ../../modules/common/base-packages.nix
    ../../modules/common/users.nix
    ../../modules/common/swapfile.nix
    ../../modules/networking/dhcp.nix
    ../../modules/ssh/server-ssh.nix
    ../../modules/server/server-setup.nix
  ];

  swapDevices = [{
    device = "/nix/swapfile";
    size = 8 * 1024;  # 8 GB in MB
  }];

  systemd.services.create-swapfile = {
    description = "Create BTRFS swapfile";
    wantedBy = [ "multi-user.target" ];
    after = [ "local-fs.target" ];
    path = [ pkgs.btrfsprogs ];
    script = ''
      if [ ! -f /nix/swapfile ]; then
        btrfs filesystem mkswapfile --size 8g --uuid clear /nix/swapfile
      fi
    '';
  };

  # Make sure the swapfile has the right attributes (COW must be disabled for swap)
  systemd.tmpfiles.rules = [
    "f /nix/swapfile 0600 root root - - -"
  ];

  # Hardware-specific settings for this server (bootloader, specific interfaces)
  # GRUB on UEFI — device = "nodev" tells GRUB to install to the mounted ESP
  boot.loader.grub = {
    enable = true;
    efiSupport = true;
    device = "nodev";
  };
  boot.loader.efi.canTouchEfiVariables = true;
  networking.interfaces.enp1s0.useDHCP = true;

  # NOTE: SSH host keys persist by default (generated once into stateful /etc/ssh);
  # no special handling is needed on a standard install.

  # CRITICAL: This tells NixOS which release cycle you're on.
  # It enables safe migrations between releases. Always set this!
  # Use the current stable release: "26.05" for NixOS Yarara (released May 2026).
  system.stateVersion = "26.05";
}
