# hosts/server/configuration.nix
{ config, lib, pkgs, inputs, ... }: {
  imports = [
    # Hardware configuration (auto-generated by NixOS — kernel modules, CPU, etc.)
    ./hardware-configuration.nix

    inputs.sops-nix.nixosModules.sops

    # Disko: declarative disk partitioning (replaces fileSystems in hardware-configuration.nix)
    inputs.disko.nixosModules.disko   # Disko NixOS module (from flake inputs)
    ./disko-config.nix                # Your disk layout (sets disko.devices)

    # Feature modules
    ../../modules/common/nix-settings.nix
    ../../modules/common/timezone.nix
    ../../modules/common/base-packages.nix
    ../../modules/common/users.nix
    ../../modules/common/gc.nix
    ../../modules/common/auto-upgrade.nix
    ../../modules/ssh/server-ssh.nix
    ../../modules/server/server-setup.nix

  ];

  sops.age.keyFile = "/var/lib/sops-nix/keys/keys.txt";
  sops.defaultSopsFile = ../../secrets/secrets.yaml;

  # Hardware-specific settings for this server (bootloader, specific interfaces)
  # GRUB on UEFI — device = "nodev" tells GRUB to install to the mounted ESP
  boot.loader.grub = {
    enable = true;
    efiSupport = true;
    device = "nodev";
  };

  boot.loader.efi = {
    efiSysMountPoint = "/boot/efi";
    canTouchEfiVariables = true;
  };
  networking.interfaces.enp1s0.useDHCP = true;

  # NOTE: SSH host keys persist by default (generated once into stateful /etc/ssh);
  # no special handling is needed on a standard install.

  # CRITICAL: This tells NixOS which release cycle you're on.
  # It enables safe migrations between releases. Always set this!
  # Use the current stable release: "26.05" for NixOS Yarara (released May 2026).
  system.stateVersion = "26.05";
}
